###getDiscograficas
GET http://localhost:3000/api/v1/Discograficas

###getDiscograficas
GET http://localhost:3000/api/v1/Discograficas/1

###getDiscograficasBanda
GET http://localhost:3000/api/v1/Discograficas?banda=Ad Hominem

###getDiscograficas No existente
GET http://localhost:3000/api/v1/Discograficas/4

###nuevoAlbum
POST http://localhost:3000/api/v1/Discograficas
Content-Type: application/json

{
  "nombre": "Totenlider",
  "isDeleted": false
}



###actualizar
PUT http://localhost:3000/api/v1/Discograficas
Content-Type: application/json

{
  "nombre": "Burzum",
  "anio": "2006",
  "banda": "Burzum",
  "genero": "Black Metal",
  "precio": 16.80
}


### Paginación y ordenación
GET http://localhost:3000/api/v1/Discograficas?sortBy=nombre&direction=asc
###
GET http://localhost:3000/api/v1/Discograficas?sortBy=nombre&direction=desc&size=1
###
GET http://localhost:3000/api/v1/Discograficas?sortBy=nombre&direction=desc&size=1&page=0

