###getDiscograficas
GET http://localhost:3000/api/v1/Discograficas

###getDiscograficas
GET http://localhost:3000/api/v1/Discograficas/1

###getDiscograficasBanda
GET http://localhost:3000/api/v1/Discograficas?banda=Dissection

###getDiscograficas No existente
GET http://localhost:3000/api/v1/Discograficas/4

###nuevoAlbum
POST http://localhost:3000/api/v1/Discograficas
Content-Type: application/json

{
  "nombre": "Totenlider",
  "anio": 2005,
  "banda": "Absurd",
  "genero": "Black Metal",
  "precio": 14.80
}



###actualizar
PUT http://localhost:3000/api/v1/Discograficas
Content-Type: application/json

{
  "nombre": "Burzum",
  "anio": "2006",
  "banda": "Burzum",
  "genero": "Black Metal",
  "precio": 16.80
}

