


type Query {
    albumes : [Album!]!

    albumesById(id: ID!): Album


    discograficas: [Discograficas!]!

    discograficasById(id: ID!): Discograficas


    discograficasByNombre(nombre: String!): [Discograficas!]!
}


type Album {
    id: ID!
    nombre: String!
    anio: String!
    banda: String!
    genero: String!
    precio: Float!
    uuid: String!
    createdAt: String!
    updatedAt: String!
    isDeleted: Boolean!
    discografica: Discograficas!



}

type Discograficas {
    id: ID!
    nombre: String!
    createdAt: String!
    updatedAt: String!
    isDeleted: Boolean!
    album: [Album!]!
}
