spring.application.name=Repaso_SpringBoot

server.port=${PORT:3000}
# Versionamos la API
api.version=${API_VERSION:v1}

server.error.include-message=always

logging.level.com.carlosvc.repaso_springboot=DEBUG