spring.application.name=Repaso_SpringBoot

server.port=${PORT:3000}
# Versionamos la API
api.version=${API_VERSION:v1}

server.error.include-message=always


logging.level.com.carlosvc.repaso_springboot=DEBUG


spring.datasource.url=jdbc:h2:mem:Albumes


spring.datasource.username=carlos

spring.h2.console.enabled=true


spring.jpa.show-sql=true


spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.secret=ShrekIsLoveIsLife
jwt.expiration=8600000