# Albumes
label.album.empty=No se han encontrado albumes
label.album.nombre=Nombre
label.album.anio=Año
label.album.banda=Banda
label.album.genero=Genero
label.album.precio=Precio
label.album.discografica=Discografica
label.album.detalle=Detalle del album
albumes.search=Buscar

# Barra de navegación
nav.home=Inicio
nav.login=Conexión
nav.logout=Cerrar Sesión
nav.new.albumes=Nuevo album
error.404=Recurso no encontrado

# Autenticación
auth.login=Iniciar Sesión
auth.register=Registrarse
auth.logout=Cerrar Sesión
auth.email=Email
auth.username=Usuario
auth.password=Contraseña
auth.remember=Recordarme
auth.forgot.password=¿Olvidaste tu contraseña?
