drop table if exists ALBUMES;
drop table if exists DISCOGRAFICAS;

create table ALBUMES(
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(20) not null ,
    anio int not null,
    banda varchar(40) not null ,
    genero varchar(40) not null ,
    precio double not null ,
    discografica_id bigint,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT  CURRENT_TIMESTAMP not null ,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null ,
    uuid uuid not null unique

);


create table DISCOGRAFICAS (
    id bigint generated by default as identity PRIMARY KEY ,
    nombre varchar(20) not null  unique ,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT  CURRENT_TIMESTAMP not null ,
    updated_at TIMESTAMP DEFAULT  CURRENT_TIMESTAMP not null
);

create table user_roles (
                            user_id bigint not null,
                            roles enum ('ADMIN','USER')
);


create table usuarios (
                          id         bigint generated by default as identity PRIMARY KEY,
                          nombre     varchar(255)                        not null,
                          apellidos  varchar(255)                        not null,
                          username   varchar(255)                        not null unique,
                          email      varchar(255)                        not null unique,
                          password   varchar(255)                        not null,
                          is_deleted boolean   default false,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                          titular_id bigint unique,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);

alter table if exists tarjetas
    add constraint fk_tarjetas_titulares_titular_id
    foreign key (titular_id)
    references titulares(id);


alter table if exists user_roles
    add constraint fk_user_roles_usuarios_user_id
    foreign key (user_id)
    references usuarios(id);

alter table if exists user_roles
    add constraint fk_user_roles_usuarios_user_id
    foreign key (user_id)
    references usuarios(id);

alter table  if exists albumes
    add constraint fk_albumes_discograficas_discografica_id foreign key (discografica_id) references DISCOGRAFICAS(id)