drop table if exists ALBUMES;
drop table if exists DISCOGRAFICAS;

create table ALBUMES(
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(20) not null ,
    anio int not null,
    banda varchar(40) not null ,
    genero varchar(40) not null ,
    precio double not null ,
    discografica_id bigint,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT  CURRENT_TIMESTAMP not null ,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null ,
    uuid uuid not null unique

);


create table DISCOGRAFICAS (
    id bigint generated by default as identity PRIMARY KEY ,
    nombre varchar(20) not null  unique ,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT  CURRENT_TIMESTAMP not null ,
    updated_at TIMESTAMP DEFAULT  CURRENT_TIMESTAMP not null
);

alter table  if exists albumes
    add constraint fk_albumes_discograficas_discografica_id foreign key (discografica_id) references DISCOGRAFICAS(id)